site_name: K0rdent
site_author: Mirantis
docs_dir: ./docs
repo_name: GitHub
repo_url: https://github.com/K0rdent/kcm
copyright:
  '© 2005 - 2025 Mirantis, Inc. All rights reserved.'
theme:
  name: "material"
  font:
    text: Overpass
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  icon: assets/mirantis-logo-inverted-horizontal-one-color.svg
  logo: assets/mirantis-logo-inverted-horizontal-one-color.svg
  favicon: assets/favicon.ico

  search: true
  search_index_only: true
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    default: latest

nav:
  - Home: index.md
  - section_1:
    - Page 1: section_1/page_1.md
    - Page 2: section_1/page_2.md
  - section_2:
    - Page 1: section_2/page_1.md
    - Page 2: section_2/page_2.md
  